# Default values for symfony.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: prod
debug: '1'
secret: ChangeMe
corsAllowOrigin: http://example.com

php:
  repository: gcr.io/symfony-4-skeleton-docker/php
  tag: latest
  pullPolicy: Always
  replicaCount: 1

nginx:
  repository: gcr.io/symfony-4-skeleton-docker/nginx
  tag: latest
  pullPolicy: Always
  replicaCount: 1

varnish:
  enabled: true
  #url: https://example.com
  repository: gcr.io/symfony-4-skeleton-docker/varnish
  tag: latest
  pullPolicy: Always
  replicaCount: 1

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  tls:
#     Secrets must be manually created in the namespace.
     - secretName: symfony-4-skeleton-docker-tls-cert
       hosts:
         - symfony-4-skeleton-docker.woprrr.info

postgresql:
  enabled: true
  # If bringing your own PostgreSQL, the full uri to use
  #url: pgsql://symfony:ChangeMe@example.com/symfony?serverVersion=9.6
  postgresUser: symfony
  postgresPassword: ChangeMe
  postgresDatabase: symfony
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
